/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_tag = 2,
  anon_sym_composite = 3,
  anon_sym_EQ = 4,
  sym_tag_reference = 5,
  anon_sym_attribute = 6,
  anon_sym_COLON = 7,
  aux_sym_attribute_reference_token1 = 8,
  anon_sym_number = 9,
  anon_sym_percentage = 10,
  anon_sym_text = 11,
  anon_sym_date = 12,
  anon_sym_time = 13,
  anon_sym_datetime = 14,
  sym_number = 15,
  sym_percentage = 16,
  aux_sym_text_token1 = 17,
  aux_sym_text_token2 = 18,
  sym_date = 19,
  sym_time = 20,
  sym_datetime = 21,
  anon_sym_where = 22,
  sym_range = 23,
  sym_line_comment = 24,
  anon_sym_POUND_POUND_POUND = 25,
  aux_sym_block_comment_token1 = 26,
  anon_sym_POUND = 27,
  aux_sym_block_comment_token2 = 28,
  anon_sym_POUND_POUND = 29,
  sym_source_file = 30,
  sym_element = 31,
  sym_decleration = 32,
  sym_tag_declaration = 33,
  sym_composite_declaration = 34,
  sym_attribute_decleration = 35,
  sym_attribute_reference = 36,
  sym_type = 37,
  sym_value = 38,
  sym_text = 39,
  sym_constraint_block = 40,
  sym_constraint_reference = 41,
  sym_constraint_element = 42,
  sym_constraint_value = 43,
  sym_comment = 44,
  sym_block_comment = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_composite_declaration_repeat1 = 47,
  aux_sym_constraint_block_repeat1 = 48,
  aux_sym_block_comment_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_tag] = "tag",
  [anon_sym_composite] = "composite",
  [anon_sym_EQ] = "=",
  [sym_tag_reference] = "tag_reference",
  [anon_sym_attribute] = "attribute",
  [anon_sym_COLON] = ":",
  [aux_sym_attribute_reference_token1] = "attribute_reference_token1",
  [anon_sym_number] = "number",
  [anon_sym_percentage] = "percentage",
  [anon_sym_text] = "text",
  [anon_sym_date] = "date",
  [anon_sym_time] = "time",
  [anon_sym_datetime] = "datetime",
  [sym_number] = "number",
  [sym_percentage] = "percentage",
  [aux_sym_text_token1] = "text_token1",
  [aux_sym_text_token2] = "text_token2",
  [sym_date] = "date",
  [sym_time] = "time",
  [sym_datetime] = "datetime",
  [anon_sym_where] = "where",
  [sym_range] = "range",
  [sym_line_comment] = "line_comment",
  [anon_sym_POUND_POUND_POUND] = "###",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_block_comment_token2] = "block_comment_token2",
  [anon_sym_POUND_POUND] = "##",
  [sym_source_file] = "source_file",
  [sym_element] = "element",
  [sym_decleration] = "decleration",
  [sym_tag_declaration] = "tag_declaration",
  [sym_composite_declaration] = "composite_declaration",
  [sym_attribute_decleration] = "attribute_decleration",
  [sym_attribute_reference] = "attribute_reference",
  [sym_type] = "type",
  [sym_value] = "value",
  [sym_text] = "text",
  [sym_constraint_block] = "constraint_block",
  [sym_constraint_reference] = "constraint_reference",
  [sym_constraint_element] = "constraint_element",
  [sym_constraint_value] = "constraint_value",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_composite_declaration_repeat1] = "composite_declaration_repeat1",
  [aux_sym_constraint_block_repeat1] = "constraint_block_repeat1",
  [aux_sym_block_comment_repeat1] = "block_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_tag] = anon_sym_tag,
  [anon_sym_composite] = anon_sym_composite,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_tag_reference] = sym_tag_reference,
  [anon_sym_attribute] = anon_sym_attribute,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_attribute_reference_token1] = aux_sym_attribute_reference_token1,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_percentage] = anon_sym_percentage,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_date] = anon_sym_date,
  [anon_sym_time] = anon_sym_time,
  [anon_sym_datetime] = anon_sym_datetime,
  [sym_number] = sym_number,
  [sym_percentage] = sym_percentage,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [aux_sym_text_token2] = aux_sym_text_token2,
  [sym_date] = sym_date,
  [sym_time] = sym_time,
  [sym_datetime] = sym_datetime,
  [anon_sym_where] = anon_sym_where,
  [sym_range] = sym_range,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_block_comment_token2] = aux_sym_block_comment_token2,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [sym_source_file] = sym_source_file,
  [sym_element] = sym_element,
  [sym_decleration] = sym_decleration,
  [sym_tag_declaration] = sym_tag_declaration,
  [sym_composite_declaration] = sym_composite_declaration,
  [sym_attribute_decleration] = sym_attribute_decleration,
  [sym_attribute_reference] = sym_attribute_reference,
  [sym_type] = sym_type,
  [sym_value] = sym_value,
  [sym_text] = sym_text,
  [sym_constraint_block] = sym_constraint_block,
  [sym_constraint_reference] = sym_constraint_reference,
  [sym_constraint_element] = sym_constraint_element,
  [sym_constraint_value] = sym_constraint_value,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_composite_declaration_repeat1] = aux_sym_composite_declaration_repeat1,
  [aux_sym_constraint_block_repeat1] = aux_sym_constraint_block_repeat1,
  [aux_sym_block_comment_repeat1] = aux_sym_block_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_tag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_composite] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_reference] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_attribute] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_percentage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_percentage] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_datetime] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_decleration] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_composite_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_decleration] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_block] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_element] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_composite_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraint_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 12,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(77);
      ADVANCE_MAP(
        '"', 2,
        '#', 142,
        ':', 105,
        '=', 101,
        '@', 73,
        'a', 46,
        'c', 37,
        'd', 11,
        'n', 52,
        'p', 15,
        't', 9,
        'w', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(126);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(142);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(140);
      if (lookahead != 0) ADVANCE(141);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(69);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(57);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(71);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'b') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(97);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(23);
      END_STATE();
    case 28:
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 35:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 54:
      if (lookahead == 'x') ADVANCE(45);
      END_STATE();
    case 55:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 56:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(143);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 73:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 74:
      if (eof) ADVANCE(77);
      if (lookahead == '#') ADVANCE(137);
      if (lookahead == '=') ADVANCE(101);
      if (lookahead == 'a') ADVANCE(93);
      if (lookahead == 'c') ADVANCE(86);
      if (lookahead == 't') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 75:
      if (eof) ADVANCE(77);
      if (lookahead == '#') ADVANCE(137);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == 'c') ADVANCE(37);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == 'w') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(75);
      END_STATE();
    case 76:
      if (eof) ADVANCE(77);
      if (lookahead == '#') ADVANCE(136);
      if (lookahead == '@') ADVANCE(73);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == 'c') ADVANCE(37);
      if (lookahead == 't') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(95);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_tag);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_tag);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_composite);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_composite);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_tag_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_attribute);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_attribute);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_attribute_reference_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_percentage);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_date);
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_time);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '-') ADVANCE(67);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '-') ADVANCE(67);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == ':') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == ':') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(124);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_percentage);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_text_token2);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_date);
      if (lookahead == 'T') ADVANCE(70);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(68);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_datetime);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == ':') ADVANCE(72);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_range);
      if (lookahead == '.') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_range);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '#') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(138);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '#') ADVANCE(135);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(138);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '#') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(138);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(141);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(141);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(145);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_block_comment_token2);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_block_comment_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(143);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(139);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 75},
  [2] = {.lex_state = 75},
  [3] = {.lex_state = 75},
  [4] = {.lex_state = 76},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 76},
  [7] = {.lex_state = 74},
  [8] = {.lex_state = 74},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 74},
  [11] = {.lex_state = 75},
  [12] = {.lex_state = 76},
  [13] = {.lex_state = 76},
  [14] = {.lex_state = 74},
  [15] = {.lex_state = 76},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 75},
  [18] = {.lex_state = 74},
  [19] = {.lex_state = 74},
  [20] = {.lex_state = 74},
  [21] = {.lex_state = 75},
  [22] = {.lex_state = 75},
  [23] = {.lex_state = 75},
  [24] = {.lex_state = 75},
  [25] = {.lex_state = 75},
  [26] = {.lex_state = 75},
  [27] = {.lex_state = 75},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 76},
  [33] = {.lex_state = 55},
  [34] = {.lex_state = 55},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 56},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 55},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 55},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_tag] = ACTIONS(1),
    [anon_sym_composite] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_attribute] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_attribute_reference_token1] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_percentage] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_date] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_percentage] = ACTIONS(1),
    [aux_sym_text_token2] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [sym_time] = ACTIONS(1),
    [sym_datetime] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [sym_range] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym_element] = STATE(3),
    [sym_decleration] = STATE(25),
    [sym_tag_declaration] = STATE(27),
    [sym_composite_declaration] = STATE(27),
    [sym_attribute_decleration] = STATE(27),
    [sym_comment] = STATE(25),
    [sym_block_comment] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_tag] = ACTIONS(3),
    [anon_sym_composite] = ACTIONS(5),
    [anon_sym_attribute] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(9),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_tag,
    ACTIONS(18), 1,
      anon_sym_composite,
    ACTIONS(21), 1,
      anon_sym_attribute,
    ACTIONS(24), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(24), 1,
      sym_block_comment,
    STATE(2), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(25), 2,
      sym_decleration,
      sym_comment,
    STATE(27), 3,
      sym_tag_declaration,
      sym_composite_declaration,
      sym_attribute_decleration,
  [35] = 10,
    ACTIONS(3), 1,
      anon_sym_tag,
    ACTIONS(5), 1,
      anon_sym_composite,
    ACTIONS(7), 1,
      anon_sym_attribute,
    ACTIONS(9), 1,
      sym_line_comment,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_block_comment,
    STATE(2), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(25), 2,
      sym_decleration,
      sym_comment,
    STATE(27), 3,
      sym_tag_declaration,
      sym_composite_declaration,
      sym_attribute_decleration,
  [70] = 5,
    ACTIONS(34), 1,
      sym_tag_reference,
    ACTIONS(36), 1,
      aux_sym_attribute_reference_token1,
    ACTIONS(38), 1,
      sym_line_comment,
    STATE(6), 2,
      sym_attribute_reference,
      aux_sym_composite_declaration_repeat1,
    ACTIONS(32), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [91] = 6,
    ACTIONS(44), 1,
      aux_sym_text_token1,
    ACTIONS(46), 1,
      aux_sym_text_token2,
    STATE(18), 1,
      sym_text,
    STATE(19), 1,
      sym_constraint_value,
    ACTIONS(40), 2,
      sym_number,
      sym_date,
    ACTIONS(42), 4,
      sym_percentage,
      sym_time,
      sym_datetime,
      sym_range,
  [114] = 5,
    ACTIONS(50), 1,
      sym_tag_reference,
    ACTIONS(53), 1,
      aux_sym_attribute_reference_token1,
    ACTIONS(56), 1,
      sym_line_comment,
    STATE(6), 2,
      sym_attribute_reference,
      aux_sym_composite_declaration_repeat1,
    ACTIONS(48), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [135] = 5,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(10), 1,
      sym_constraint_reference,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
    STATE(8), 2,
      sym_constraint_element,
      aux_sym_constraint_block_repeat1,
    ACTIONS(62), 4,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [156] = 5,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(10), 1,
      sym_constraint_reference,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
    STATE(8), 2,
      sym_constraint_element,
      aux_sym_constraint_block_repeat1,
    ACTIONS(69), 4,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [177] = 6,
    ACTIONS(75), 1,
      aux_sym_text_token1,
    ACTIONS(77), 1,
      aux_sym_text_token2,
    STATE(13), 1,
      sym_value,
    STATE(15), 1,
      sym_text,
    ACTIONS(71), 2,
      sym_number,
      sym_date,
    ACTIONS(73), 3,
      sym_percentage,
      sym_time,
      sym_datetime,
  [199] = 3,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(81), 5,
      sym_identifier,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [214] = 4,
    ACTIONS(87), 1,
      anon_sym_where,
    ACTIONS(89), 1,
      sym_line_comment,
    STATE(26), 1,
      sym_constraint_block,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [231] = 2,
    ACTIONS(93), 1,
      sym_line_comment,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      sym_tag_reference,
      anon_sym_attribute,
      aux_sym_attribute_reference_token1,
      anon_sym_POUND_POUND_POUND,
  [244] = 2,
    ACTIONS(97), 1,
      sym_line_comment,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      sym_tag_reference,
      anon_sym_attribute,
      aux_sym_attribute_reference_token1,
      anon_sym_POUND_POUND_POUND,
  [257] = 2,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(101), 5,
      sym_identifier,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [270] = 2,
    ACTIONS(105), 1,
      sym_line_comment,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      sym_tag_reference,
      anon_sym_attribute,
      aux_sym_attribute_reference_token1,
      anon_sym_POUND_POUND_POUND,
  [283] = 3,
    ACTIONS(109), 1,
      anon_sym_date,
    STATE(11), 1,
      sym_type,
    ACTIONS(107), 5,
      anon_sym_number,
      anon_sym_percentage,
      anon_sym_text,
      anon_sym_time,
      anon_sym_datetime,
  [297] = 2,
    ACTIONS(113), 1,
      sym_line_comment,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_where,
      anon_sym_POUND_POUND_POUND,
  [309] = 2,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(117), 5,
      sym_identifier,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [321] = 2,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(121), 5,
      sym_identifier,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [333] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(93), 5,
      sym_identifier,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      sym_line_comment,
  [345] = 2,
    ACTIONS(125), 1,
      sym_line_comment,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [356] = 2,
    ACTIONS(129), 1,
      sym_line_comment,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [367] = 2,
    ACTIONS(133), 1,
      sym_line_comment,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [378] = 2,
    ACTIONS(137), 1,
      sym_line_comment,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [389] = 2,
    ACTIONS(141), 1,
      sym_line_comment,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [400] = 2,
    ACTIONS(145), 1,
      sym_line_comment,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [411] = 2,
    ACTIONS(149), 1,
      sym_line_comment,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
      anon_sym_POUND_POUND_POUND,
  [422] = 4,
    ACTIONS(151), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(153), 1,
      aux_sym_block_comment_token1,
    STATE(28), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(156), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
  [436] = 4,
    ACTIONS(159), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(161), 1,
      aux_sym_block_comment_token1,
    STATE(28), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(163), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
  [450] = 4,
    ACTIONS(165), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(167), 1,
      aux_sym_block_comment_token1,
    STATE(29), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(163), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
  [464] = 2,
    ACTIONS(169), 1,
      aux_sym_block_comment_token1,
    ACTIONS(151), 3,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
  [473] = 3,
    ACTIONS(36), 1,
      aux_sym_attribute_reference_token1,
    ACTIONS(171), 1,
      sym_tag_reference,
    STATE(4), 2,
      sym_attribute_reference,
      aux_sym_composite_declaration_repeat1,
  [484] = 3,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(10), 1,
      sym_constraint_reference,
    STATE(7), 2,
      sym_constraint_element,
      aux_sym_constraint_block_repeat1,
  [495] = 1,
    ACTIONS(175), 1,
      sym_identifier,
  [499] = 1,
    ACTIONS(177), 1,
      anon_sym_COLON,
  [503] = 1,
    ACTIONS(179), 1,
      anon_sym_EQ,
  [507] = 1,
    ACTIONS(181), 1,
      aux_sym_block_comment_token2,
  [511] = 1,
    ACTIONS(183), 1,
      anon_sym_EQ,
  [515] = 1,
    ACTIONS(185), 1,
      sym_identifier,
  [519] = 1,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
  [523] = 1,
    ACTIONS(189), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 91,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 177,
  [SMALL_STATE(10)] = 199,
  [SMALL_STATE(11)] = 214,
  [SMALL_STATE(12)] = 231,
  [SMALL_STATE(13)] = 244,
  [SMALL_STATE(14)] = 257,
  [SMALL_STATE(15)] = 270,
  [SMALL_STATE(16)] = 283,
  [SMALL_STATE(17)] = 297,
  [SMALL_STATE(18)] = 309,
  [SMALL_STATE(19)] = 321,
  [SMALL_STATE(20)] = 333,
  [SMALL_STATE(21)] = 345,
  [SMALL_STATE(22)] = 356,
  [SMALL_STATE(23)] = 367,
  [SMALL_STATE(24)] = 378,
  [SMALL_STATE(25)] = 389,
  [SMALL_STATE(26)] = 400,
  [SMALL_STATE(27)] = 411,
  [SMALL_STATE(28)] = 422,
  [SMALL_STATE(29)] = 436,
  [SMALL_STATE(30)] = 450,
  [SMALL_STATE(31)] = 464,
  [SMALL_STATE(32)] = 473,
  [SMALL_STATE(33)] = 484,
  [SMALL_STATE(34)] = 495,
  [SMALL_STATE(35)] = 499,
  [SMALL_STATE(36)] = 503,
  [SMALL_STATE(37)] = 507,
  [SMALL_STATE(38)] = 511,
  [SMALL_STATE(39)] = 515,
  [SMALL_STATE(40)] = 519,
  [SMALL_STATE(41)] = 523,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_declaration, 4, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_composite_declaration, 4, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_block, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_block, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_element, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_element, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_decleration, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_decleration, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_reference, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_reference, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_reference, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_reference, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_value, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_value, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_element, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_element, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_declaration, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_declaration, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_decleration, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_decleration, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decleration, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decleration, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [187] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gct(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gct",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
