/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_tag = 2,
  anon_sym_composite = 3,
  anon_sym_EQ = 4,
  sym_tag_reference = 5,
  anon_sym_attribute = 6,
  aux_sym_attribute_reference_token1 = 7,
  anon_sym_number = 8,
  anon_sym_percentage = 9,
  anon_sym_text = 10,
  anon_sym_date = 11,
  anon_sym_time = 12,
  anon_sym_datetime = 13,
  sym_number = 14,
  sym_percentage = 15,
  aux_sym_text_token1 = 16,
  aux_sym_text_token2 = 17,
  sym_date = 18,
  sym_time = 19,
  sym_datetime = 20,
  sym_source_file = 21,
  sym_element = 22,
  sym_tag_declaration = 23,
  sym_composite_declaration = 24,
  sym_attribute_decleration = 25,
  sym_attribute_reference = 26,
  sym_type = 27,
  sym_value = 28,
  sym_text = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_composite_declaration_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_tag] = "tag",
  [anon_sym_composite] = "composite",
  [anon_sym_EQ] = "=",
  [sym_tag_reference] = "tag_reference",
  [anon_sym_attribute] = "attribute",
  [aux_sym_attribute_reference_token1] = "attribute_reference_token1",
  [anon_sym_number] = "number",
  [anon_sym_percentage] = "percentage",
  [anon_sym_text] = "text",
  [anon_sym_date] = "date",
  [anon_sym_time] = "time",
  [anon_sym_datetime] = "datetime",
  [sym_number] = "number",
  [sym_percentage] = "percentage",
  [aux_sym_text_token1] = "text_token1",
  [aux_sym_text_token2] = "text_token2",
  [sym_date] = "date",
  [sym_time] = "time",
  [sym_datetime] = "datetime",
  [sym_source_file] = "source_file",
  [sym_element] = "element",
  [sym_tag_declaration] = "tag_declaration",
  [sym_composite_declaration] = "composite_declaration",
  [sym_attribute_decleration] = "attribute_decleration",
  [sym_attribute_reference] = "attribute_reference",
  [sym_type] = "type",
  [sym_value] = "value",
  [sym_text] = "text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_composite_declaration_repeat1] = "composite_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_tag] = anon_sym_tag,
  [anon_sym_composite] = anon_sym_composite,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_tag_reference] = sym_tag_reference,
  [anon_sym_attribute] = anon_sym_attribute,
  [aux_sym_attribute_reference_token1] = aux_sym_attribute_reference_token1,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_percentage] = anon_sym_percentage,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_date] = anon_sym_date,
  [anon_sym_time] = anon_sym_time,
  [anon_sym_datetime] = anon_sym_datetime,
  [sym_number] = sym_number,
  [sym_percentage] = sym_percentage,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [aux_sym_text_token2] = aux_sym_text_token2,
  [sym_date] = sym_date,
  [sym_time] = sym_time,
  [sym_datetime] = sym_datetime,
  [sym_source_file] = sym_source_file,
  [sym_element] = sym_element,
  [sym_tag_declaration] = sym_tag_declaration,
  [sym_composite_declaration] = sym_composite_declaration,
  [sym_attribute_decleration] = sym_attribute_decleration,
  [sym_attribute_reference] = sym_attribute_reference,
  [sym_type] = sym_type,
  [sym_value] = sym_value,
  [sym_text] = sym_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_composite_declaration_repeat1] = aux_sym_composite_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_tag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_composite] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_reference] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_attribute] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_percentage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_percentage] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_datetime] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_composite_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_decleration] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_composite_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(65);
      ADVANCE_MAP(
        '"', 2,
        '#', 63,
        '=', 69,
        '@', 64,
        'a', 38,
        'c', 30,
        'd', 7,
        'n', 44,
        'p', 11,
        't', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(92);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(59);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(61);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(67);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 46:
      if (lookahead == 'x') ADVANCE(37);
      END_STATE();
    case 47:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 63:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 64:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_tag);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_composite);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_tag_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_attribute);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_attribute_reference_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_percentage);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_date);
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_time);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == ':') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == ':') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (lookahead == '.') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_percentage);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_text_token2);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_date);
      if (lookahead == 'T') ADVANCE(60);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(58);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_datetime);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == ':') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 47},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 47},
  [19] = {.lex_state = 47},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_tag] = ACTIONS(1),
    [anon_sym_composite] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_tag_reference] = ACTIONS(1),
    [anon_sym_attribute] = ACTIONS(1),
    [aux_sym_attribute_reference_token1] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_percentage] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_date] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_percentage] = ACTIONS(1),
    [aux_sym_text_token2] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [sym_time] = ACTIONS(1),
    [sym_datetime] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_element] = STATE(2),
    [sym_tag_declaration] = STATE(12),
    [sym_composite_declaration] = STATE(12),
    [sym_attribute_decleration] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_tag] = ACTIONS(3),
    [anon_sym_composite] = ACTIONS(5),
    [anon_sym_attribute] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_tag,
    ACTIONS(5), 1,
      anon_sym_composite,
    ACTIONS(7), 1,
      anon_sym_attribute,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(12), 3,
      sym_tag_declaration,
      sym_composite_declaration,
      sym_attribute_decleration,
  [22] = 6,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(16), 1,
      anon_sym_composite,
    ACTIONS(19), 1,
      anon_sym_attribute,
    STATE(3), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(12), 3,
      sym_tag_declaration,
      sym_composite_declaration,
      sym_attribute_decleration,
  [44] = 6,
    ACTIONS(26), 1,
      aux_sym_text_token1,
    ACTIONS(28), 1,
      aux_sym_text_token2,
    STATE(8), 1,
      sym_text,
    STATE(10), 1,
      sym_value,
    ACTIONS(22), 2,
      sym_number,
      sym_date,
    ACTIONS(24), 3,
      sym_percentage,
      sym_time,
      sym_datetime,
  [66] = 4,
    ACTIONS(32), 1,
      sym_tag_reference,
    ACTIONS(34), 1,
      aux_sym_attribute_reference_token1,
    STATE(6), 2,
      sym_attribute_reference,
      aux_sym_composite_declaration_repeat1,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
  [83] = 4,
    ACTIONS(38), 1,
      sym_tag_reference,
    ACTIONS(41), 1,
      aux_sym_attribute_reference_token1,
    STATE(6), 2,
      sym_attribute_reference,
      aux_sym_composite_declaration_repeat1,
    ACTIONS(36), 4,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
  [100] = 3,
    ACTIONS(46), 1,
      anon_sym_date,
    STATE(13), 1,
      sym_type,
    ACTIONS(44), 5,
      anon_sym_number,
      anon_sym_percentage,
      anon_sym_text,
      anon_sym_time,
      anon_sym_datetime,
  [114] = 1,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      sym_tag_reference,
      anon_sym_attribute,
      aux_sym_attribute_reference_token1,
  [123] = 1,
    ACTIONS(50), 6,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      sym_tag_reference,
      anon_sym_attribute,
      aux_sym_attribute_reference_token1,
  [132] = 1,
    ACTIONS(52), 6,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      sym_tag_reference,
      anon_sym_attribute,
      aux_sym_attribute_reference_token1,
  [141] = 1,
    ACTIONS(54), 4,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
  [148] = 1,
    ACTIONS(56), 4,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
  [155] = 1,
    ACTIONS(58), 4,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
  [162] = 1,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      anon_sym_tag,
      anon_sym_composite,
      anon_sym_attribute,
  [169] = 3,
    ACTIONS(34), 1,
      aux_sym_attribute_reference_token1,
    ACTIONS(62), 1,
      sym_tag_reference,
    STATE(5), 2,
      sym_attribute_reference,
      aux_sym_composite_declaration_repeat1,
  [180] = 1,
    ACTIONS(64), 1,
      sym_identifier,
  [184] = 1,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
  [188] = 1,
    ACTIONS(68), 1,
      sym_identifier,
  [192] = 1,
    ACTIONS(70), 1,
      sym_identifier,
  [196] = 1,
    ACTIONS(72), 1,
      anon_sym_EQ,
  [200] = 1,
    ACTIONS(74), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 83,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 123,
  [SMALL_STATE(10)] = 132,
  [SMALL_STATE(11)] = 141,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 155,
  [SMALL_STATE(14)] = 162,
  [SMALL_STATE(15)] = 169,
  [SMALL_STATE(16)] = 180,
  [SMALL_STATE(17)] = 184,
  [SMALL_STATE(18)] = 188,
  [SMALL_STATE(19)] = 192,
  [SMALL_STATE(20)] = 196,
  [SMALL_STATE(21)] = 200,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_declaration, 4, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_composite_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_reference, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_declaration, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_decleration, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [66] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gct(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gct",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
